# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import transmission.tenseal_shapley.tenseal_shapley_data_pb2 as tenseal__shapley__data__pb2


class MIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sum_enc_all_reduce = channel.unary_unary(
                '/MIService/sum_enc_all_reduce',
                request_serializer=tenseal__shapley__data__pb2.all_reduce_msg.SerializeToString,
                response_deserializer=tenseal__shapley__data__pb2.all_reduce_msg.FromString,
                )
        self.sum_enc_batch = channel.unary_unary(
                '/MIService/sum_enc_batch',
                request_serializer=tenseal__shapley__data__pb2.batch_msg.SerializeToString,
                response_deserializer=tenseal__shapley__data__pb2.batch_msg.FromString,
                )


class MIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sum_enc_all_reduce(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sum_enc_batch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sum_enc_all_reduce': grpc.unary_unary_rpc_method_handler(
                    servicer.sum_enc_all_reduce,
                    request_deserializer=tenseal__shapley__data__pb2.all_reduce_msg.FromString,
                    response_serializer=tenseal__shapley__data__pb2.all_reduce_msg.SerializeToString,
            ),
            'sum_enc_batch': grpc.unary_unary_rpc_method_handler(
                    servicer.sum_enc_batch,
                    request_deserializer=tenseal__shapley__data__pb2.batch_msg.FromString,
                    response_serializer=tenseal__shapley__data__pb2.batch_msg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sum_enc_all_reduce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MIService/sum_enc_all_reduce',
            tenseal__shapley__data__pb2.all_reduce_msg.SerializeToString,
            tenseal__shapley__data__pb2.all_reduce_msg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sum_enc_batch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MIService/sum_enc_batch',
            tenseal__shapley__data__pb2.batch_msg.SerializeToString,
            tenseal__shapley__data__pb2.batch_msg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
