# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tenseal_shapley_data.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1atenseal_shapley_data.proto\"2\n\x0e\x61ll_reduce_msg\x12\x13\n\x0b\x63lient_rank\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\x0c\"N\n\tbatch_msg\x12\x13\n\x0b\x63lient_rank\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\x0c\x12\x12\n\ngroup_keys\x18\x03 \x03(\x05\x12\x0b\n\x03res\x18\x04 \x03(\x0c\x32l\n\tMIService\x12\x36\n\x12sum_enc_all_reduce\x12\x0f.all_reduce_msg\x1a\x0f.all_reduce_msg\x12\'\n\rsum_enc_batch\x12\n.batch_msg\x1a\n.batch_msgb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tenseal_shapley_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ALL_REDUCE_MSG']._serialized_start=30
  _globals['_ALL_REDUCE_MSG']._serialized_end=80
  _globals['_BATCH_MSG']._serialized_start=82
  _globals['_BATCH_MSG']._serialized_end=160
  _globals['_MISERVICE']._serialized_start=162
  _globals['_MISERVICE']._serialized_end=270
# @@protoc_insertion_point(module_scope)
